=== AjaxMultiCommentary/ajmc/data/templates/page.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://impresso.github.io/impresso-schemas/json/commentary/page.schema.json",
  "title": "Commmentary Page",
  "description": "Physical representation of a commentary page as recognized by a given OCR engine.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Canonical ID of the commentary page."
    },
    "iiif": {
      "type": "string",
      "description": "URI of the IIIF Manifest of the commentary page image."
    },
    "cdate": {
      "type": "string",
      "description": "Creation date timestamp (of the JSON file)."
    },
    "regions": {
      "type": "array",
      "description": "Page regions.",
      "items": {
        "type": "object",
        "description": "Page region.",
        "properties": {
          "region_type": {
            "type":"string",
            "description": "The type of olr region, (e.g. commentary, primary_text,...)"
          },
          "bbox": {
            "type": "array",
            "description": "Coordinates of image-region, following IIIF regions schema (x, y, width, height).",
            "minItems": 4,
            "items": {
              "type": "integer"
            }
          },
          "lines": {
            "type": "array",
            "description": "Lines of text (belonging to a given paragraph)",
            "items": {
              "type": "object",
              "properties": {
                "bbox": {
                  "type": "array",
                  "description": "Coordinates of image-region.",
                  "minItems": 4,
                  "items": {
                    "type": "integer"
                  }
                },
                "words": {
                  "type": "array",
                  "description": "Tokens (as detected by the OCR engine).",
                  "items": {
                    "type": "object",
                    "properties": {
                      "bbox": {
                        "type": "array",
                        "description": "Coordinates of image-region.",
                        "minItems": 4,
                        "items": {
                          "type": "integer"
                        }
                      },
                      "text": {
                        "type": "string",
                        "description": "Token surface form."
                      }
                    },
                    "required": [
                      "bbox",
                      "text"
                    ]
                  }
                }
              },
              "required": [
                "bbox",
                "words"
              ]
            }
          }
        },
        "required": [
          "bbox",
          "lines"
        ]
      }
    }
  },
  "required": [
    "id",
    "cdate",
    "regions"
  ]
}

=== AjaxMultiCommentary/ajmc/tests/data/cu31924087948174/ner/annotation/3464N4_tess_retrained/jsons/cu31924087948174_0051.json
{
  "iiif": "None",
  "id": "cu31924087948174_0051",
  "cdate": "2024-03-19 15:41:16",
  "regions": [
    {
      "region_type": "commentary",
      "bbox": [
        121,
        1299,
        560,
        886
      ],
      "lines": [
        {
          "bbox": [
            121,
            1299,
            554,
            31
          ],
          "words": [
            {
              "bbox": [
                121,
                1299,
                43,
                26
              ],
              "text": "the"
            },
            {
              "bbox": [
                173,
                1300,
                91,
                25
              ],
              "text": "former"
            },
            {
              "bbox": [
                276,
                1300,
                46,
                30
              ],
              "text": "(I),"
            },
            {
              "bbox": [
                334,
                1300,
                46,
                24
              ],
              "text": "but"
            },
            {
              "bbox": [
                392,
                1300,
                20,
                24
              ],
              "text": "it"
            },
            {
              "bbox": [
                421,
                1299,
                87,
                25
              ],
              "text": "makes"
            },
            {
              "bbox": [
                516,
                1300,
                81,
                24
              ],
              "text": "better"
            },
            {
              "bbox": [
                606,
                1307,
                69,
                17
              ],
              "text": "sense"
            }
          ]
        },
        {
          "bbox": [
            122,
            1332,
            554,
            33
          ],
          "words": [
            {
              "bbox": [
                122,
                1336,
                28,
                22
              ],
              "text": "to"
            },
            {
              "bbox": [
                162,
                1333,
                54,
                32
              ],
              "text": "join"
            },
            {
              "bbox": [
                227,
                1333,
                44,
                24
              ],
              "text": "the"
            },
            {
              "bbox": [
                282,
                1333,
                92,
                24
              ],
              "text": "adverb"
            },
            {
              "bbox": [
                389,
                1332,
                59,
                25
              ],
              "text": "here"
            },
            {
              "bbox": [
                461,
                1333,
                62,
                24
              ],
              "text": "with"
            },
            {
              "bbox": [
                537,
                1333,
                42,
                24
              ],
              "text": "the"
            },
            {
              "bbox": [
                593,
                1332,
                83,
                25
              ],
              "text": "whole"
            }
          ]
        },
        {
          "bbox": [
            121,
            1360,
            555,
            42
          ],
          "words": [
            {
              "bbox": [
                121,
                1366,
                157,
                32
              ],
              "text": "expression"
            },
            {
              "bbox": [
                270,
                1360,
                12,
                42
              ],
              "text": ";"
            },
            {
              "bbox": [
                295,
                1366,
                43,
                24
              ],
              "text": "i.e."
            },
            {
              "bbox": [
                353,
                1368,
                53,
                25
              ],
              "text": "not,"
            },
            {
              "bbox": [
                424,
                1364,
                71,
                26
              ],
              "text": "‘You"
            },
            {
              "bbox": [
                510,
                1365,
                87,
                25
              ],
              "text": "shrink"
            },
            {
              "bbox": [
                611,
                1366,
                65,
                24
              ],
              "text": "from"
            }
          ]
        },
        {
          "bbox": [
            123,
            1397,
            553,
            33
          ],
          "words": [
            {
              "bbox": [
                123,
                1399,
                82,
                31
              ],
              "text": "seeing"
            },
            {
              "bbox": [
                217,
                1406,
                15,
                16
              ],
              "text": "a"
            },
            {
              "bbox": [
                243,
                1406,
                59,
                16
              ],
              "text": "man"
            },
            {
              "bbox": [
                311,
                1398,
                57,
                24
              ],
              "text": "who"
            },
            {
              "bbox": [
                381,
                1398,
                20,
                24
              ],
              "text": "is"
            },
            {
              "bbox": [
                411,
                1398,
                92,
                31
              ],
              "text": "clearly"
            },
            {
              "bbox": [
                509,
                1397,
                102,
                29
              ],
              "text": "insane,’"
            },
            {
              "bbox": [
                621,
                1398,
                55,
                29
              ],
              "text": "but,"
            }
          ]
        },
        {
          "bbox": [
            124,
            1430,
            552,
            33
          ],
          "words": [
            {
              "bbox": [
                124,
                1430,
                162,
                26
              ],
              "text": "Youshrink"
            },
            {
              "bbox": [
                295,
                1431,
                64,
                24
              ],
              "text": "from"
            },
            {
              "bbox": [
                371,
                1430,
                84,
                33
              ],
              "text": "seeing"
            },
            {
              "bbox": [
                463,
                1431,
                96,
                32
              ],
              "text": "plainly"
            },
            {
              "bbox": [
                570,
                1440,
                16,
                16
              ],
              "text": "a"
            },
            {
              "bbox": [
                596,
                1431,
                80,
                25
              ],
              "text": "man’s"
            }
          ]
        },
        {
          "bbox": [
            121,
            1463,
            552,
            32
          ],
          "words": [
            {
              "bbox": [
                121,
                1464,
                130,
                25
              ],
              "text": "madness.’"
            },
            {
              "bbox": [
                294,
                1463,
                46,
                32
              ],
              "text": "Cp."
            },
            {
              "bbox": [
                364,
                1463,
                55,
                25
              ],
              "text": "infr."
            },
            {
              "bbox": [
                445,
                1471,
                55,
                24
              ],
              "text": "229,"
            },
            {
              "bbox": [
                523,
                1463,
                150,
                32
              ],
              "text": "περίφαντος."
            }
          ]
        },
        {
          "bbox": [
            121,
            1496,
            554,
            33
          ],
          "words": [
            {
              "bbox": [
                121,
                1496,
                56,
                25
              ],
              "text": "The"
            },
            {
              "bbox": [
                197,
                1505,
                68,
                16
              ],
              "text": "same"
            },
            {
              "bbox": [
                283,
                1497,
                119,
                32
              ],
              "text": "meaning"
            },
            {
              "bbox": [
                421,
                1505,
                59,
                24
              ],
              "text": "may"
            },
            {
              "bbox": [
                498,
                1497,
                32,
                25
              ],
              "text": "be"
            },
            {
              "bbox": [
                548,
                1497,
                127,
                30
              ],
              "text": "obtained,"
